services:
  fastapi:
    build: .
    restart: always
    user: airflow
    ports:
      - "8000:8000"
    volumes:
      - ./app:/opt/airflow/app
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    working_dir: /opt/airflow
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  streamlit:
    image: python:3.11-slim
    container_name: streamlit-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      - SAVE_DIR=/app/app/model
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: >
      bash -c "pip install streamlit pandas joblib deep-translator textblob xgboost lightgbm scikit-learn dill boto3 && 
      python -m streamlit run app.py --server.port=8501 --server.address=0.0.0.0"